version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - API_KEY=some-api-key
      - AUTH__SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_shop
    networks:
      - web_network

volumes:
  postgres_data:

networks:
  web_network:
